services:
  varnish:
    image: varnish:stable
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./app/default.vcl:/etc/varnish/default.vcl
  app:
    environment:
      reverse_proxy_present: 1