services:
  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      discovery.type: single-node
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: cambiar a clave de su
    ports:
      - "9200:9200"
      - "9600:9600"

volumes:
  esdata:
